export enum FontFamily {
  ARIAL = "Arial",
  CURSIVE = "Cursive",
  TIMES_NEW_ROMAN = "Times New Roman",
  VERDANA = "Verdana",
  HELVETICA = "Helvetica",
  GARAMOND = "Garamond",
  FANTASY = "Fantasy",
  MONOSPACE = "Monospace",
  COURIER_NEW = "Courier New",
  GEORGIA = "Georgia",
  PALATINO = "Palatino",
  IMPACT = "Impact",
  TAHOMA = "Tahoma",
  COMIC_SANS_MS = "Comic Sans MS",
  TREBUCHET_MS = "Trebuchet MS",
  LUCIDA_GRANDE = "Lucida Grande",
  CENTURY_GOTHIC = "Century Gothic",
  CALIBRI = "Calibri",
  BOOKMAN_OLD_STYLE = "Bookman Old Style",
  COPPERPLATE = "Copperplate",
  BRUSH_SCRIPT_MT = "Brush Script MT",
  FRANKLIN_GOTHIC_MEDIUM = "Franklin Gothic Medium",
  GILL_SANS = "Gill Sans",
  OPTIMA = "Optima",
  SANS_SERIF = "Sans-serif",
  SERIF = "Serif",
}
